name: "Zoom Transcript Upload"
on:
  workflow_dispatch:
    inputs:
      MEETING_ID:
        description: "Zoom meeting ID for which to fetch transcript"
        required: true
      DISCOURSE_CATEGORY:
        description: "Discourse category ID"
        required: false
        default: "63"

jobs:
  upload_transcript:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Publish Transcript to Discourse
        run: |
          python -m modules.cli publish-transcript \
            --meeting-id "${{ github.event.inputs.MEETING_ID }}" \
            --category-id "${{ github.event.inputs.DISCOURSE_CATEGORY }}"
        env:
          ZOOM_CLIENT_ID: ${{ secrets.ZOOM_CLIENT_ID }}
          ZOOM_CLIENT_SECRET: ${{ secrets.ZOOM_CLIENT_SECRET }}
          ZOOM_ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_API_KEY }}
          DISCOURSE_API_USERNAME: ${{ secrets.DISCOURSE_API_USERNAME }}
          DISCOURSE_BASE_URL: ${{ vars.DISCOURSE_BASE_URL }}