name: "YouTube Video Uploader"

on:
  workflow_dispatch:
    inputs:
      MEETING_ID:
        description: "Zoom meeting ID to process"
        required: true
  schedule:
    - cron: "0 */4 * * *"  # Still run every 4 hours

jobs:
  youtube-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install google-api-python-client
          pip install -r requirements.txt

      - name: Upload Zoom recording to YouTube
        run: |
          python scripts/upload_zoom_recording.py \
            --meeting_id "${{ github.event.inputs.MEETING_ID }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZOOM_CLIENT_ID: ${{ secrets.ZOOM_CLIENT_ID }}
          ZOOM_CLIENT_SECRET: ${{ secrets.ZOOM_CLIENT_SECRET }}
          ZOOM_ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

